### ISSUE TITLE
Formatting issues with [voucher_print]

### ISSUE THREAD

**Issue by Ark74** [mohamedhagag/dvit-odoo#5]
I've installed and tested the plugin voucher_print] it works fine, but it has some issues with the formatting of the header on the receipts generated.

![Image of Issue](https://cloud.githubusercontent.com/assets/7444518/18146883/b2c55da4-6f97-11e6-98a7-612b7959238e.png)

Thanks in advance for you attention.

**Comment by mohamedhagag** [comment]
Yes, this is because of the default layout_header view, to fix it you have to make header empty.

Will fix it in our module soon,

Regards,

**Comment by Ark74** [comment]
You are right.
Deleted line 11 
`    <t t-call="report.external_layout_header"/>`
on Views » external_layout

The header is gone and it looks better.
![fixed-views](https://cloud.githubusercontent.com/assets/7444518/18172165/ffff5894-7029-11e6-91f8-7ea90d4d6849.png)

Does the module should overwrite that function(?) instead of deleting lines on Views?
Maybe formatting the header to a longer and thinner version could allow it to stay.

Thanks for your advice.
